# Vagrantfile

Vagrant.configure("2") do |config|
  # Use the ubuntu/jammy64 base box
  config.vm.box = "ubuntu/jammy64"

  # Configure VM resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"      # Set memory to 1 GB
    vb.cpus = 2            # Set CPU count to 2
  end

  # Define VM hostname
  config.vm.hostname = "ubuntu-jammy-vm"

  # Provisioning script (optional)
  config.vm.provision "file", source: "../shellscript/custum_k8s_manage.sh", destination: "/tmp/custum_k8s_manage.sh"
  config.vm.provision "shell", inline: <<-SHELL
    # Install utilities and run the Kubernetes management script
	sudo rm -f /etc/machine-id /var/lib/dbus/machine-id
	sudo dbus-uuidgen --ensure=/var/lib/dbus/machine-id
	sudo ln -s /var/lib/dbus/machine-id /etc/machine-id
	sudo sed -i '/jammy/d' /etc/hosts  &>/dev/null
	sudo sed -i '/ubuntu/d' /etc/hosts  &>/dev/null
	sudo apt-get update
    sudo apt-get install -y dos2unix net-tools
    sudo dos2unix /tmp/custum_k8s_manage.sh
	bash -x /tmp/custum_k8s_manage.sh
  SHELL
end
