# Vagrantfile
K8S_IP_NW = "192.168.56."
M_IP_START = 40
W_IP_START = 50
k8master_hostname="k8smaster01"
SHELL_FILE_PATH = "../shellscript/deploy_ngx_metlb.sh"

Vagrant.configure("2") do |config|
  # Use the ubuntu/jammy64 base box
  config.vm.define "k8smst" do |k8mst01|
    k8mst01.vm.box = "ubuntu/jammy64"
    k8mst01.vm.hostname = k8master_hostname
    k8mst01.vm.network "private_network", ip: "#{K8S_IP_NW}#{M_IP_START}"
  end
  # Configure VM resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"      # Set memory to 1 GB
    vb.cpus = 6            # Set CPU count to 2
  end

  # Provisioning script (optional)
  config.vm.provision "file", source: SHELL_FILE_PATH, destination: "/tmp/run_me_shell.sh"
  config.vm.provision "shell", inline: <<-SHELL
    # Install utilities and run the Kubernetes management script
	sudo rm -f /etc/machine-id /var/lib/dbus/machine-id
	sudo dbus-uuidgen --ensure=/var/lib/dbus/machine-id
	sudo ln -s /var/lib/dbus/machine-id /etc/machine-id
	sudo sed -i '/jammy/d' /etc/hosts  &>/dev/null
	sudo sed -i '/ubuntu/d' /etc/hosts  &>/dev/null
	sudo apt-get update
    sudo apt-get install -y dos2unix net-tools
    sudo dos2unix /tmp/run_me_shell.sh
	bash -x /tmp/run_me_shell.sh
  SHELL
end
